project_id      = "minecraftneedsloof"
region          = "europe-west3"
zone            = "europe-west3-c"
rcon_password   = "iYL1DQkR9FTnkJZRo7RN3O1rrMosO4NW"
local_world_zip = "./files/world.zip"
local_sa_keys   = "./files/keys/tfsa.json"
machine_type    = "e2-medium"
