project_id    = "minecraftneedsloof2"
region        = "europe-west3"
zone          = "europe-west3-c"
rcon_password = "JigglesAreBountiful"
local_world_zip = "./files/world.zip"
local_sa_keys = "./files/keys/test.json"
